'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { FileText } from 'lucide-react';
import { PatientInfoSection } from './PatientInfoSection';
import { ObjectiveSection } from './ObjectiveSection';
import { AssessmentSection } from './AssessmentSection';
import { PlanSection } from './PlanSection';
import { FallbackNote } from './FallbackNote';

interface StructuredClinicalNoteProps {
  structuredNote: string;
  flaggedWords: string[];
  objective?: {
    content: string;
    categories: {
      mentalStatusExam: string;
      physicalObservations: string;
      behavioralObservations: string;
    };
  };
  assessment?: {
    content: string;
    categories: {
      primaryDiagnosis: string;
      differentialDiagnoses: string;
      riskAssessment: string;
    };
  };
  plan?: {
    content: string;
    categories: {
      immediateInterventions: string;
      treatmentRecommendations: string;
      followUpPlan: string;
      safetyMeasures: string;
    };
  };
}

export default function StructuredClinicalNote({
  structuredNote,
  flaggedWords,
  objective,
  assessment,
  plan,
}: StructuredClinicalNoteProps) {
  return (
    <Card className="border-0 shadow-lg bg-slate-50">
      <CardHeader className="bg-white border-b border-slate-200 px-8 py-6">
        <CardTitle className="flex items-center justify-between text-slate-900">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-blue-50 rounded-lg">
              <FileText className="size-5 text-blue-600" />
            </div>
            <div>
              <span className="text-xl font-semibold">
                Structured Clinical Note
              </span>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <span className="bg-blue-50 text-blue-700 px-3 py-1 rounded-full text-xs font-medium">
              SOAP Format
            </span>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="p-8">
        <ScrollArea className="h-[500px]">
          <div className="space-y-6">
            {/* Patient Information */}
            <PatientInfoSection
              structuredNote={structuredNote}
              flaggedWords={flaggedWords}
            />

            {/* SOAP Format Sections */}
            <div className="space-y-6">
              {/* Objective */}
              <ObjectiveSection
                objective={objective}
                flaggedWords={flaggedWords}
              />

              {/* Assessment */}
              <AssessmentSection
                assessment={assessment}
                flaggedWords={flaggedWords}
              />

              {/* Plan */}
              <PlanSection plan={plan} flaggedWords={flaggedWords} />
            </div>

            {/* Fallback Note */}
            <FallbackNote
              structuredNote={structuredNote}
              objective={objective}
            />

            {/* Footer with metadata */}
            <div className="border-t border-slate-200 pt-6 mt-8">
              <div className="flex items-center justify-between text-xs text-slate-500">
                <span className="flex items-center space-x-2">
                  <div className="size-2 bg-blue-500 rounded-full" />
                  <span>Generated by AI Clinical Assistant</span>
                </span>
                <span>{new Date().toLocaleString()}</span>
              </div>
            </div>
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
